// Code generated by protoc-gen-bic. DO NOT EDIT.
// versions: 2.0.3

import request, { Response } from "@/utils/axiosReq";
import { IEmpty } from "./common.pb";

export enum EMenuItemType {
  MenuItemType_none = 0,
  MenuItemType_folder = 1,
  MenuItemType_document = 2
}
export interface IRouteMeta {
  title?: string | null;
  icon?: string | null;
  rank?: string | null;
  auths?: string[] | null;
}

export interface IRouteItem {
  meta?: IRouteMeta | null;
  path?: string | null;
  name?: string | null;
  key?: string | null;
  children?: IRouteItem[] | null;
  actions?: string[] | null;
}

export interface IRouteItem {
  meta?: IRouteMeta | null;
  path?: string | null;
  name?: string | null;
  key?: string | null;
  children?: IRouteItem[] | null;
  actions?: string[] | null;
}

export interface IResponseRoute {
  item_list?: IRouteItem[] | null;
}

export interface IRequestRoute {
  __placeholder__?: any;
}

export interface IRoleItem {
  id: number | null;
  name: string | null;
  create_time?: number | null; // 创建时间
  create_user?: string | null; // 创建用户
  update_time?: number | null; // 更新时间
  update_user?: string | null; // 更新用户
  remark?: string | null; // 备注
  father_id?: number | null; // 父角色ID
  father_name?: string | null; // 父角色名
}

export interface IResponseRoles {
  data_list?: IRoleItem[] | null;
}

export interface IPageItem {
  id: string | null;
  label?: string | null;
  checked?: boolean | null;
}

export interface IRouteNode {
  id: string | null;
  label?: string | null;
  items?: IPageItem[] | null;
  children?: IRouteNode[] | null;
}

export interface IRouteNode {
  id: string | null;
  label?: string | null;
  items?: IPageItem[] | null;
  children?: IRouteNode[] | null;
}

export interface IResponseGetRole {
  id: number | null;
  name: string | null;
  create_time?: number | null; // 创建时间
  create_user?: string | null; // 创建用户
  update_time?: number | null; // 更新时间
  update_user?: string | null; // 更新用户
  remark?: string | null; // 备注
  father_id?: number | null; // 父角色ID
  father_name?: string | null; // 父角色名
  route_list?: IRouteNode[] | null;
}

export interface IHttpMethod {
  url: string | null;
  method: string | null;
  note?: string | null;
}

export interface IMenuPageAction {
  id: string | null;
  label?: string | null;
  methods?: IHttpMethod[] | null; // 对应http接口
}

export interface IItemMenu {
  id: string | null;
  label: string | null;
  menu_item_type: EMenuItemType | null;
  items?: IMenuPageAction[] | null;
  children?: IItemMenu[] | null;
}

export interface IItemMenu {
  id: string | null;
  label: string | null;
  menu_item_type: EMenuItemType | null;
  items?: IMenuPageAction[] | null;
  children?: IItemMenu[] | null;
}

export interface IResponseGetMenus {
  route_list?: IItemMenu[] | null;
}

export interface IRequestPostMenuAction {
  key: string | null;
  label: string | null;
  apis?: string[] | null; // 对应api key列表
}

export interface IRequestPatchMenuPageAction {
  key: string | null;
  label: string | null;
  methods?: IHttpMethod[] | null; // 对应http接口
}

export interface IApiItem {
  key: string | null;
  url: string | null;
  method: string | null;
  label: string | null;
}

export interface IResponseApis {
  api_list?: IApiItem[] | null;
}

export interface IItemApi {
  Key: string | null;
  Url: string | null;
  Method: string | null;
  Label: string | null;
}

export interface IItemMenuAction {
  key: string | null;
  label: string | null;
  Api_list?: IItemApi[] | null; // 对应http接口
}

export interface IResponseGetMenuAction {
  action_list?: IItemMenuAction[] | null;
}

// 获取接口列表
export function GetApis(): Promise<Response<IResponseApis>> {
  return request({
    url: "/v1/apis",
    method: "GET"
  });
}

// 获取路由
export function GetRoutes(): Promise<Response<IResponseRoute>> {
  return request({
    url: "/v1/routes",
    method: "GET"
  });
}

// 获取角色列表
export function GetRoles(): Promise<Response<IResponseRoles>> {
  return request({
    url: "/v1/roles",
    method: "GET"
  });
}

/**
 * 获取角色详情
 * @Param { number } id -
 */
export function GetRole(id: number): Promise<Response<IResponseGetRole>> {
  return request({
    url: "/v1/role/" + id,
    method: "GET"
  });
}

// 获取菜单列表
export function GetMenus(): Promise<Response<IResponseGetMenus>> {
  return request({
    url: "/v1/menus",
    method: "GET"
  });
}

/**
 * 获取菜单
 * @Param { string } key -
 */
export function GetMenuAction(
  key: string
): Promise<Response<IResponseGetMenuAction>> {
  return request({
    url: "/v1/menu/" + key + "/action",
    method: "GET"
  });
}

/**
 * 添加菜单页面行为
 * @Param { string } key -
 */
export function PostMenuAction(
  key: string,
  data: IRequestPostMenuAction
): Promise<Response<IEmpty>> {
  return request({
    url: "/v1/menu/" + key + "/action",
    method: "POST",
    data
  });
}

// 修改菜单页面行为
export function PatchMenuAction(
  data: IRequestPostMenuAction
): Promise<Response<IEmpty>> {
  return request({
    url: "/v1/menu/action",
    method: "PATCH",
    data
  });
}
