// Code generated by protoc-gen-bic. DO NOT EDIT.
// versions: 2.0.0

import request, { Response } from "@/utils/axiosReq";
import { IEmpty } from "./common.pb";

export interface IRouteMeta {
  title?: string | null;
  icon?: string | null;
  rank?: string | null;
  auths?: string[] | null;
}

export interface IRouteItem {
  meta?: IRouteMeta | null;
  path?: string | null;
  name?: string | null;
  key?: string | null;
  children?: IRouteItem[] | null;
}

export interface IRouteItem {
  meta?: IRouteMeta | null;
  path?: string | null;
  name?: string | null;
  key?: string | null;
  children?: IRouteItem[] | null;
}

export interface IResponseRoute {
  item_list?: IRouteItem[] | null;
}

export interface IRequestRoute {
  __placeholder__?: any;
}

export interface IRoleItem {
  id: number;
  name: string;
  create_time?: number | null; // 创建时间
  create_user?: string | null; // 创建用户
  update_time?: number | null; // 更新时间
  update_user?: string | null; // 更新用户
  remark?: string | null; // 备注
  father_id?: number | null; // 父角色ID
  father_name?: string | null; // 父角色名
}

export interface IResponseRoles {
  data_list?: IRoleItem[] | null;
}

export interface IResponseGetRole {
  id: number;
  name: string;
  create_time?: number | null; // 创建时间
  create_user?: string | null; // 创建用户
  update_time?: number | null; // 更新时间
  update_user?: string | null; // 更新用户
  remark?: string | null; // 备注
  father_id?: number | null; // 父角色ID
  father_name?: string | null; // 父角色名
}

// 获取路由
export function GetRoutes(): Promise<Response<IResponseRoute>> {
  return request({
    url: "/v1/routes/",
    method: "GET"
  });
}

// 获取角色列表
export function GetRoles(): Promise<Response<IResponseRoles>> {
  return request({
    url: "/v1/roles/",
    method: "GET"
  });
}

/**
 * 获取角色详情
 * @Param { number } id -
 */
export function GetRole(id: number): Promise<Response<IResponseGetRole>> {
  return request({
    url: "/v1/role/" + id + "/",
    method: "GET"
  });
}
