// Code generated by protoc-gen-bic. DO NOT EDIT.
// versions: 2.0.2

import request, { Response } from "@/utils/axiosReq";

export interface IRequestAuth {
  username: string | null; // 用户名
  password: string | null; // 密码
}

export interface IResponseAuth {
  token: string | null;
  expires: number | null;
  token_refresh: string | null;
  expires_refresh: number | null;
  username?: string | null;
  roles?: string[] | null;
}

export interface IRequestRefreshToken {
  token_refresh: string | null;
}

// 登录
export function PostAuth(data: IRequestAuth): Promise<Response<IResponseAuth>> {
  return request({
    url: "/v1/auth",
    method: "POST",
    data
  });
}

// 刷新token
export function PostRefreshToken(
  data: IRequestRefreshToken
): Promise<Response<IResponseAuth>> {
  return request({
    url: "/v1/token/refresh",
    method: "POST",
    data
  });
}
