// Code generated by protoc-gen-bic. DO NOT EDIT.
// versions: 2.0.0

import request, { Response } from "@/utils/axiosReq";

export interface IRequestUsers {
  page: number; // 页码
  page_size: number; // 每页数量
  username?: string | null;
  email?: string | null;
}

export interface IUser {
  id: number; // 主键ID
  username?: string | null; // 用户名
  name?: string | null; // 姓名
  email: string; // 邮箱
  update_time: number; // 活跃时间戳
  ban?: boolean | null; // 账号是否禁用
}

export interface IResponseUsers {
  page?: number | null;
  page_size?: number | null;
  total?: number | null;
  data_list?: IUser[] | null;
}

// 获取用户列表
export function GetUsers(
  params: IRequestUsers
): Promise<Response<IResponseUsers>> {
  return request({
    url: "/v1/users/",
    method: "GET",
    params
  });
}
